version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PWD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB=${MYSQL_DATABASE}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - acme_network

volumes:
  db_data:

networks:
  acme_network:
    driver: bridge