entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: domsanton@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
      # caserver: https://acme-staging-v02.api.letsencrypt.org/directory
